// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
       // return macos;
      case TargetPlatform.windows:
       // return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx50EcDoQUjcUDu8w_x6tXywo8NktInKw',
    appId: '1:1013367715256:web:860d4186c5265867380b4d',
    messagingSenderId: '1013367715256',
    projectId: 'buddybot-dc6b5',
    authDomain: 'buddybot-dc6b5.firebaseapp.com',
    storageBucket: 'buddybot-dc6b5.firebasestorage.app',
    measurementId: 'G-KZVYS0BSBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_hu6aPUat_-vICiWDJ5MbEcp2Hae2OLg',
    appId: '1:1013367715256:android:0fbb26886688bd64380b4d',
    messagingSenderId: '1013367715256',
    projectId: 'buddybot-dc6b5',
    storageBucket: 'buddybot-dc6b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyGxKeZzgAkaZtDZOjCspcDaflzDR9Qgs',
    appId: '1:1013367715256:ios:849cc1b1041c7efa380b4d',
    messagingSenderId: '1013367715256',
    projectId: 'buddybot-dc6b5',
    storageBucket: 'buddybot-dc6b5.firebasestorage.app',
    iosBundleId: 'com.example.buddybot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyGxKeZzgAkaZtDZOjCspcDaflzDR9Qgs',
    appId: '1:1013367715256:ios:849cc1b1041c7efa380b4d',
    messagingSenderId: '1013367715256',
    projectId: 'buddybot-dc6b5',
    storageBucket: 'buddybot-dc6b5.firebasestorage.app',
    iosBundleId: 'com.example.buddybot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx50EcDoQUjcUDu8w_x6tXywo8NktInKw',
    appId: '1:1013367715256:web:1653878641ca2743380b4d',
    messagingSenderId: '1013367715256',
    projectId: 'buddybot-dc6b5',
    authDomain: 'buddybot-dc6b5.firebaseapp.com',
    storageBucket: 'buddybot-dc6b5.firebasestorage.app',
    measurementId: 'G-LH506T6BN8',
  );

}